[build]
  command = "npm run build --no-lint"
  publish = ".next"

[build.environment]
  PRISMA_GENERATE_DATAPROXY = "true"

[context.production.environment]
  DATABASE_URL = "prisma://aws-us-east-2.prisma-data.com/?api_key=YOUR_PRISMA_ACCELERATE_API_KEY"
  DIRECT_DATABASE_URL = "postgresql://jackerboxDB_owner:npg_vYM7Pg4ERIAk@ep-fancy-wind-a5ymnajb-pooler.us-east-2.aws.neon.tech/jackerboxDB?sslmode=require"
  NEXTAUTH_URL = "https://jackerbox.netlify.app"
  NEXTAUTH_SECRET = "your-nextauth-secret"
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME = "dgtqpyphg"
  CLOUDINARY_API_KEY = "646841252992477"
  CLOUDINARY_API_SECRET = "Zxu873QWGlD6cYq2gB9cqFO6wG0"
  CLOUDINARY_URL = "cloudinary://646841252992477:Zxu873QWGlD6cYq2gB9cqFO6wG0@dgtqpyphg"
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyAJEWRG3nYv_iX87UrUiIiv8zu6q2NFwSA"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "jackerbox-8fd7c.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "jackerbox-8fd7c"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "jackerbox-8fd7c.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "145612880895"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:145612880895:web:6303f4eeb3f8c7fbed05ca"
  STRIPE_SECRET_KEY = "sk_test_51QnoIsGzpz6fWtnwD4AksuP7edt6C7eirjZJItIEjhRQI1yjx972rCdrWUfPxCIdNF3v2LfICx6UEuhHhebg7pEJ00Rs4dcUzq"
  STRIPE_PUBLISHABLE_KEY = "pk_test_51QnoIsGzpz6fWtnwD4j9Y01vLyuH8jI3NudJjrP2Q9SuKoPKwlk8ciYKPzGiXtVPnIPMdWt0WIzMQSw0TAZIPL6v00m97FooMa"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_51QnoIsGzpz6fWtnwD4j9Y01vLyuH8jI3NudJjrP2Q9SuKoPKwlk8ciYKPzGiXtVPnIPMdWt0WIzMQSw0TAZIPL6v00m97FooMa"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# For client-side routing with Next.js static export
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/image*"
  to = "/_next/image:splat"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = true 