build:
  command: chmod +x setup-ui.sh && ./setup-ui.sh && npm run build --no-lint
  publish: .next
  environment:
    NETLIFY_NEXT_PLUGIN_SKIP: "true"
    NODE_VERSION: "20"
    PRISMA_GENERATE_DATAPXY: "true"

plugins:
  - package: '@netlify/plugin-nextjs' 