[build]
  command = "chmod +x setup-ui.sh && ./setup-ui.sh && npm run build:simple"
  publish = ".next"

[build.environment]
  PRISMA_GENERATE_DATAPROXY = "true"
  NODE_VERSION = "20"

[context.production.environment]
  DATABASE_URL = "${PRISMA_ACCELERATE_URL}"
  DIRECT_DATABASE_URL = "${DIRECT_DATABASE_URL}"
  NEXTAUTH_URL = "https://jackerbox.netlify.app"
  NEXTAUTH_SECRET = "${NEXTAUTH_SECRET}"
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME = "${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}"
  CLOUDINARY_API_KEY = "${CLOUDINARY_API_KEY}"
  CLOUDINARY_API_SECRET = "${CLOUDINARY_API_SECRET}"
  CLOUDINARY_URL = "${CLOUDINARY_URL}"
  NEXT_PUBLIC_FIREBASE_API_KEY = "${NEXT_PUBLIC_FIREBASE_API_KEY}"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "${NEXT_PUBLIC_FIREBASE_PROJECT_ID}"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}"
  NEXT_PUBLIC_FIREBASE_APP_ID = "${NEXT_PUBLIC_FIREBASE_APP_ID}"
  STRIPE_SECRET_KEY = "${STRIPE_SECRET_KEY}"
  STRIPE_PUBLISHABLE_KEY = "${STRIPE_PUBLISHABLE_KEY}"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# For client-side routing with Next.js static export
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/image*"
  to = "/_next/image:splat"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = true 