[build]
  command = "npm run build:netlify"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "20"
  PRISMA_GENERATE_DATAPROXY = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs" 