#!/bin/bash

# Create a new Netlify configuration file for static export
cat > netlify.toml << 'EOL'
[build]
  command = "chmod +x setup-ui.sh && ./setup-ui.sh && NODE_OPTIONS='--max-old-space-size=4096' npm run build:simple"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"

[context.production.environment]
  DATABASE_URL = "${DIRECT_DATABASE_URL}"
  DIRECT_DATABASE_URL = "${DIRECT_DATABASE_URL}"
  NEXTAUTH_URL = "https://jackerbox.netlify.app"
  NEXTAUTH_SECRET = "${NEXTAUTH_SECRET}"
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME = "${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}"
  CLOUDINARY_API_KEY = "${CLOUDINARY_API_KEY}"
  CLOUDINARY_API_SECRET = "${CLOUDINARY_API_SECRET}"
  CLOUDINARY_URL = "${CLOUDINARY_URL}"
  NEXT_PUBLIC_FIREBASE_API_KEY = "${NEXT_PUBLIC_FIREBASE_API_KEY}"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "${NEXT_PUBLIC_FIREBASE_PROJECT_ID}"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}"
  NEXT_PUBLIC_FIREBASE_APP_ID = "${NEXT_PUBLIC_FIREBASE_APP_ID}"
  STRIPE_SECRET_KEY = "${STRIPE_SECRET_KEY}"
  STRIPE_PUBLISHABLE_KEY = "${STRIPE_PUBLISHABLE_KEY}"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}"
  NEXT_PUBLIC_STATIC_ONLY = "true"

# For client-side routing with Next.js static export
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
EOL

echo "Netlify configuration updated for static export!" 